version: "3.4"
services:
  react:
    build: ./frontend
    ports:
      - "5173:5173"

  express:
    build: ./Backend
    ports:
      - "4000:4000"
    depends_on:
      - neo4j

  flask:
    build: ./PythonBackend
    ports:
      - "5000:5000"
    depends_on:
      - redis

  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"

  redis:
    image: redis
    ports:
      - "6379:6379"
