module.exports = {
  Username: {
    type: "string",
    unique: true,
  },
  FirstName: "string",
  LastName: "string",
  Email: {
    type: "string",
    unique: true,
  },
  Password: "string",
  Country: "string",
  IsActive: "boolean",
  CreatedBy: "int",
  CreateDate: "string",
  Rate: "int",
  DateOfBirth: "string",
  Gender: "string",
  Work: "string",
  Bio: "string",
  LastTimeOnline: "datetime",
  chat_with_AI: {
    type: "relationship",
    target: "AIChat",
    relationship: "CHAT_WITH_AI",
    direction: "out",
    eager: true,
  },
  has_a_skill: {
    type: "relationship",
    target: "Skill",
    relationship: "HAS_A_SKILL",
    direction: "out",
    eager: true,
  },
  learn_a: {
    type: "relationship",
    target: "Education",
    relationship: "LEARN_A",
    direction: "out",
    eager: true,
  },
  has_a_social_media: {
    type: "relationship",
    target: "SocialMediaLink",
    relationship: "HAS_A_SOCIAL_MEDIA",
    direction: "out",
    eager: true,
  },
  chat_with: {
    type: "relationship",
    target: "Chat",
    relationship: "CHAT_WITH",
    direction: "out",
    eager: true,
  },
  friend_to: {
    type: "relationship",
    target: "User",
    relationship: "FRIEND_TO",
    direction: "out",
    eager: true,
  },
  send_to_company: {
    type: "relationship",
    target: "ContactMessage",
    relationship: "SEND_TO_COMPANY",
    direction: "out",
    eager: true,
  },
  apply_to: {
    type: "relationship",
    target: "PositionPost",
    relationship: "APPLY_TO",
    direction: "out",
    eager: true,
  },
  write_comment: {
    type: "relationship",
    target: "Comment",
    relationship: "WRITE_COMMENT",
    direction: "out",
    eager: true,
  },
  has_a_task: {
    type: "relationship",
    target: "Task",
    relationship: "HAS_A_TASK",
    direction: "out",
    eager: true,
  },
  in_team: {
    type: "relationship",
    target: "Team",
    relationship: "IN_TEAM",
    direction: "out",
    eager: true,
  },
};
